# Generated by Django 4.2.5 on 2023-10-12 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniplanner', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='module',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='usermodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniplanner.module')),
            ],
        ),
    ]
