# Generated by Django 4.2.5 on 2023-10-12 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniplanner', '0004_alter_module_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='toask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toask', models.TextField()),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniplanner.module')),
            ],
        ),
        migrations.CreateModel(
            name='deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniplanner.module')),
            ],
        ),
    ]
