# Generated by Django 4.2.5 on 2023-10-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplanner', '0006_deadline_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='toask',
            name='answered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
