# Generated by Django 4.2.5 on 2023-10-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniplanner', '0007_toask_answered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='priority',
            field=models.CharField(default='no', max_length=10),
            preserve_default=False,
        ),
    ]
